function co2weeklymlo = import_co2_concentration(filename, dataLines)
%IMPORTFILE Import data from a text file
%  CO2WEEKLYMLO = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  CO2WEEKLYMLO = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  co2weeklymlo = importfile("C:\Users\MW86ZB\OneDrive - Aalborg Universitet\Dokumenter\Work\teaching\matrix_computation\spring_2021\linear_reg\co2_weekly_mlo.txt", [50, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 24-Nov-2020 08:07:38

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [50, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 16);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["year", "month", "day", "year_dec", "co2_ppm", "days", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16"];
opts.SelectedVariableNames = ["year", "month", "day", "year_dec", "co2_ppm", "days"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, ["Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16"], "EmptyFieldRule", "auto");

% Import the data
co2weeklymlo = readtable(filename, opts);

end